{{- if .Values.env.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: {{ .Values.env.secret.vaultPath }}
    {{- include "application.annotations" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.env.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
