{{- if eq .Values.workload.type "CronJob" -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "web-app.fullname" . }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
  annotations:
    {{- include "web-app.annotations" . |  nindent 4 }}
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
{{- include "web-app.podTemplate" . | nindent 4 }}
{{- include "web-app.restartPolicy" . | nindent 10 }}
{{- end -}}