{{- if eq .Values.workload.type "Deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-app.fullname" . }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
  annotations:
    {{- include "web-app.annotations" . |  nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.workload.replicas }}
  {{- end -}}
  {{ toYaml .Values.workload.deployment | nindent 2 }}
  selector:
    matchLabels:
      {{- include "web-app.selectorLabels" . | nindent 6 }}
  template: {{ template "web-app.podTemplate" . }}
{{- end -}}