{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := include "web-app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "web-app.fullname" . }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingressRoute.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "web-app.annotations" . |  nindent 4 }}
spec:
  entryPoints:
  {{- range .Values.ingressRoute.entrypoint }}
    - {{ . }}
  {{- end }}
  routes:
  {{- range .Values.ingressRoute.routes }}
    - kind: Rule
      match: {{ . }}
      services:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
  {{- end }}
  {{- if .Values.ingressRoute.tls }}
  tls:
    {{- with .Values.ingressRoute.tls }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end -}}
{{- end -}}