apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geth-exporter.fullname" . }}
  labels:
    {{- include "geth-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
{{- if .Values.configuration.structuredConfig -}}
  {{ toYaml .Values.configuration.structuredConfig | nindent 4 }}
  {{- else -}}
  {{ .Values.configuration.config | nindent 4 }}
{{- end -}}